disabled_rules:
  - function_body_length
  - type_body_length
  - line_length
  - vertical_whitespace
  - orphaned_doc_comment
  - for_where
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
