# SwiftLint Configuration for MessengerAI

# Paths to include/exclude
included:
  - MessageAI/MessageAI

excluded:
  - Pods
  - MessageAI/MessageAITests
  - MessageAI/MessageAIUITests  
  - CloudFunctions
  - .build
  - DerivedData
  - node_modules

# Disabled rules
disabled_rules:
  - todo
  - trailing_whitespace

# Custom rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_comments: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - db
    - to
    - at
    - by

# Reporter type
reporter: "xcode"
